git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

os:
  editPreset: 'nvim'
  edit: 'nvim'
  editAtLine: 'nvim +{{line}}'
  editAtLineAndWait: 'nvim +{{line}}'
  openDirInEditor: 'nvim {{dir}}'

gui:
  # Show file tree by default
  showFileTree: true
  # Show command log
  showCommandLog: true
  # Mouse support
  mouseEvents: true
  # Border
  border: 'rounded'

# Custom commands can be added here
customCommands:
  - key: 'E'
    command: 'nvim {{.SelectedFile.Name}}'
    context: 'files'
    description: 'Open in neovim'
